#!/bin/sh

. /etc/ha.d/resource.d//hto-mapfuncs

usage() {
    echo "usage: $0 elastic-ip-address interface [private-ip-address|_] AWS_IAM_ROLE $LEGAL_ACTIONS"
    exit 1
}

# Check the arguments passed to this script
if [ $# -lt 3 ]; then
    usage
fi

if [ "x$2" != "x" ]; then
    OCF_RESKEY_address="$1"; shift
    export OCF_RESKEY_address
fi

if [ "x$2" != "x" ]; then
    OCF_RESKEY_interface="$1"; shift
    export OCF_RESKEY_interface
fi

if [ "x$2" != "x" ]; then
    OCF_RESKEY_privateip="$1"; shift
    export OCF_RESKEY_privateip
fi

if [ "x$2" != "x" ]; then
    OCF_RESKEY_aws_role="$1"; shift
    export OCF_RESKEY_aws_role
fi

OCF_TYPE=AWS_EIP
OCF_RESOURCE_INSTANCE=${OCF_TYPE}_${OCF_RESKEY_address}_${OCF_RESKEY_interface}
export OCF_TYPE OCF_RESOURCE_INSTANCE

ra_execocf  $1

